### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by daudix-UFO**

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Battery item is not translatable

image

**Review by corecoding — APPROVED** [review]

**Comment by corecoding** [comment]
Why is Battery not translatable?

**Comment by corecoding** [comment]
Oh, I noticed in your translation "b" in battery is lowercase. If you make it Battery it should translate.

**Comment by daudix-UFO** [comment]
gotcha, will fix this

**Pull request merged**
