### PR TITLE
Add proper NVIDIA gpu support

### PR DESCRIPTION
**Pull request by Arastais**
This PR adds a group in the extension for any NVIDIA gpus, displaying their power, temperature, clocks, utilization, etc., thus resolving #313. I essentially took the existing code base from the nvidia branch (based on #313) and rebased it on top of the main branch. I then added a few fixes and features, including but not limited to:

- Fix the gpu groups missing their status text (i.e. they would just show "No Data" even though the nvidia-smi process was functioning properly)
- Proper multi-gpu support (shows a new group for each gpu)
- The title for each gpu group is just "Graphics #" instead of the name of the gpu itself. If you just have one gpu, then it just says "Graphics". The name of the gpu is now within the group.
- The temperature and fan speed of each gpu is also shown under the temperature and fan groups, respectively. They are called "GPU #" (or just "GPU" if you only have one).
- Shows temperature, power, fan, memory, encoder/decoder and pcie stats.
- Shows static gpu info (mainly driver/bios info) if it's toggled with a setting, similar to the "include static info" setting for the processor.

Here's what the settings menu looks like:
image

(Excuse the long screenshots)
Here's what it looks like with static info turned off:
image

and with it turned on (too long to fully fit on the screen):
| First Half | Second Half |
|--|--|
| image | image |

</br>

Here's an example of the GPU fan/temperature showing in the main groups:
| Fan | Temperature
|-|-|
| image | image |

</br>

Here's an example of having many gpus, without static info (note: since my system only has one gpu, I just duplicated my gpu info 4 times for debugging purposes, and artificially changed the data on the last one):
image

</br>

There are still issues (although quite minor) with this PR however. Most notably, the items get added to the group in the wrong order compared to how they are supposed to be added in the code. This is most noticeable with multiple GPU fans: 
image
Past the second GPU, the fan gets added after the average/min/max.
Another similar example is within any gpu group. The frequency stats are added in the wrong order (all 3 frequency stats are supposed to be back-to-back):
image

Therefore, __I think it's important for multiple people, each with different systems, to test this PR out fully before it's ready for production.__ Not to mention, there could be other issues that I have personally missed. 

</br>

If this PR is merged, the best next steps in my opinion would be:
1. Consider changing the icon for the gpu. I think it's a bit too high detail to be seen at such low sizes and thus doesn't match the simplistic look of the other icons.
2. Merge the nvidia branch into the development branch and eventually make this an actual feature of the extension

### CODE REVIEW

**Comment by Arastais** [comment]
> At first glance this looks amazing. I will be finding time soon to review the PR in detail. Just didn't want to leave you hanging. Thank you!!

No worries, take your time. I realize it's a relatively large PR and hence why I feel it's important to test it on multiple systems.

I should also mention I've ran into another issue in the meantime: If there are too many items under the gpu group (which is very likely if you include static info) to fully fit on the screen, then the group/tab won't open up at all. The vitals UI will just close when you try to open the gpu tab. Maybe the maximum height of the gpu list (i.e. the height before it stops getting taller and instead just uses a scrollbar) needs to be adjusted?

**Comment by corecoding** [comment]
Hey there - this PR has some code conflicts with the current corecoding:nvidia branch. I took a look, but without Nvidia hardware readily available, I fear I'd break some of the other author contributions. Would you mind pulling the latest corecoding:nvidia and have a look? Thank you so much.

**Comment by Arastais** [comment]
Hi, thanks for the response.

That's intentional. To create this PR, I rebased the existing upstream corecoding:nvidia (which was very outdated) on top of the (much more recent) upstream corecoding:main (at the time of when I started this PR). I then added my own changes on top of that.

So, the code conflicts are to be expected; You probably either need to force push this merge request or change the base branch that this PR comapres to. If you change the base branch to corecoding:main, you'll see that this the case.

**Comment by corecoding** [comment]
I'm glad to hear about rebasing from main. I was reviewing the code in the develop branch realized I wanted to rewrite some of the merged PRs (none from the Nvidia support). Reverting the PRs in develop was too much work so I created a new develop branch from main and am cherry picking the ones I'm comfortable with.

The changes looks really solid. I love how the command line tool is updated with the sensor update interval. Side note, the code I saw for grouping sensors (multiple GPUs) should help with the multiple battery support which was exactly what I wanted to refactor. 

Anyhow, my son has an older Nvidia GPU laptop, so I was able to test this branch. For the most part it worked really well! There were some NaN values though. I took some screenshots - one is my terminal outputting info which I think is where the NaN for the fan was coming from. It also put in NaN for the normal Fan section when Nvidia was enabled.

Screenshot from 2024-01-13 22-44-20
Screenshot from 2024-01-13 22-44-29
Screenshot from 2024-01-13 22-45-49
Screenshot from 2024-01-13 22-46-17
Screenshot from 2024-01-13 22-46-35

**Comment by Arastais** [comment]
> There were some NaN values though. I took some screenshots - one is my terminal outputting info which I think is where the NaN for the fan was coming from. It also put in NaN for the normal Fan section when NVIDIA was enabled.

Interesting. I didn't run into this issue myself at all, but maybe on specific cards (e.g. maybe cards without a fan) or drivers, `nvidia-smi` can't report the fan speed. I think the best course of action is to just ignore the fan speed (or maybe any value) if its NaN (or more specifically, N/A).

---

_As a side note, I just wanted to point this specific issue out; I thought I resolved it, but that doesn't seem to be the case as it's still occurring for you:_

An issue I did run into though was there being both a `GPU` label and `GPU 1` + `GPU 2`, just like you see in the images you posted. To explain this: in the code base, the `GPU` label is actually just the same device as `GPU 1` (i.e. in code, they have the same key/group). If there are multiple gpus, then the `GPU` label gets renamed to `GPU 1`, and the other GPUs get added as `GPU #`. This is the same for the graphics group itself (e.g. "Graphics" versus "Graphics 1"/"Graphics 2").

</br>

During my testing I ran into an issue where two `nvidia-smi` output lines can get received as a single read (Again, I don't fully understand why this happens). In other words, two output lines will be perceived as one, and thus the extension will think there are multiple GPUs. This would cause a blank "Graphics 2" group, and likewise a `GPU 1` fan and blank `GPU 2` fan instead of just a `GPU` fan. Similarly, I added a fail-safe for this issue in which multiple GPUs would only get recognized and added if there were multiple consecutive reads with two or more lines. 


<details><summary>Likewise (for additional context, although this isn't relevant to this specific issue):</summary>
<p>
An `nvidia-smi` output line would only get received partially on one read, and the rest would be received on the next read. (I don't exactly know why this happens). In other words, a single `nvidia-smi` output would get split up into two lines. This would cause the graphics group to be disabled. To prevent this, I added a fail-safe where it just ignores a couple anomalous readings if it's they're wrong length (i.e. only a partial reading). Only if there are several incorrect readings back-to-back does the graphics group then get disabled. 
</p>
</details> 

</br>

With all that being said, the fact that the GPU fan issue occurring for you, even after the fail-safe I added, concerns me. Unlike the original issue, it strangely only affects the main fan group, and not the graphics group (i.e. there's no 'Graphics 2', the 'Graphics' group is how it should be). Not only that, but there's both a `GPU` and `GPU 1` label. This means that it could be the original issue (and this the fail-safe doesn't cover all bases), or it's a separate problem altogether; I myself would think something else is going on, but I'm not too sure.

**Comment by detherminal** [comment]
Please merge this, many users are waiting for this @corecoding

**Pull request merged**
