### PR TITLE
Add Support for multiple batteries

### LINKED ISSUE #263: Display two batteries at the same time
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I've got one of those Thinkpads with two batteries. In the settings menu I can check the independent percentages of battery power left _(screenshot added)_, but in the regular top bar it only displays an average percentage. With Vitals I cna at least choose which battery I'd like to see the percentage of, but I would really like it if it would be possible to view both percentages at the same time.

Screenshot from 2022-06-02 12-34-29

### PR DESCRIPTION
**Pull request by kritzl**
Fix #263

### CODE REVIEW

**Comment by kritzl** [comment]
image

Unfortunately, the values in the bar are displayed a bit offset as soon as values of batteries are selected.
So far I have not been able to find out why - maybe someone can help here.

**Comment by kritzl** [comment]
Fixed the alignment - don't know why the content was aligned to `START` in the first place...

**Comment by kritzl** [comment]
Would love to see this feature in the next update :)
If you have some time to revise the PR, that would be great @corecoding

**Comment by corecoding** [comment]
Just merged, will try to look at it this weekend. Thank you!

**Pull request merged**
