### PR TITLE
Update symbolics

### PR DESCRIPTION
**Pull request by daudix**
Update all symbolic icons to match the new GNOME symbolic style

Preview

### Icons sources:

- Battery and Storage are from the [Adwaita Icon Theme](https://gitlab.gnome.org/GNOME/adwaita-icon-theme)

- Network (receive, transmit, transmit-receive), System and Voltage are from the [Icon Development Kit](https://gitlab.gnome.org/Teams/Design/icon-development-kit)

- Fan is a bit modified current one

- Temperature, Memory and CPU are custom icons by me

_This is #291, moved to a separate branch_

### CODE REVIEW

**Comment by Nokse22** [comment]
Nice icons, more similar to the gnome ones.

**Comment by corecoding** [comment]
Thank you for the icons. I am a little partial to the existing icons, possibly because it was gratifying when I found license free versions (as the README credits). I saw a few people chime in saying they liked the new icons. This is good.

I am wondering if we had a drop-down in settings that allowed users to switch between the two?

**Comment by daudix-UFO** [comment]
Idea with icon pack switcher is interesting!

**Comment by halfmexican** [comment]
Would love to see this get merged!

**Comment by corecoding** [comment]
Anyone want to work on a UI selector to switch the icons from set 1 (existing) to set 2 (this one) ?

**Comment by SmartFinn** [comment]
@corecoding 

> I am a little partial to the existing icons, possibly because it was gratifying when I found license free versions (as the README credits).

Probably it will sounds rude, but the current icons ([memory-symbolic.svg](https://github.com/corecoding/Vitals/blob/main/icons/memory-symbolic.svg), [cpu-symbolic.svg](https://github.com/corecoding/Vitals/blob/main/icons/cpu-symbolic.svg), and [temperature-symbolic.svg](https://github.com/corecoding/Vitals/blob/main/icons/temperature-symbolic.svg)) are blurred, because pixel alignment is missing. I am checking time-to-time when you merge this PR to finally install this extension instead system-monitor-applet.

**Comment by gweebg** [comment]
> Anyone want to work on a UI selector to switch the icons from set 1 (existing) to set 2 (this one) ?

I am currently working on this, I will open a PR with this feature is still desired.

**Pull request closed without merging**
